namespace NymphsCoreManager.Models;

public sealed record NymphModuleManifestInfo(
    string Id,
    string Name,
    string ShortName,
    string Category,
    string Kind,
    string Packaging,
    string Version,
    string Description,
    string OverviewDetail,
    IReadOnlyList<NymphModuleActionLinkInfo> OverviewLinks,
    string ManifestUrl,
    string RepositoryUrl,
    string SourceSummary,
    string InstallRoot,
    IReadOnlyList<NymphModuleActionFieldInfo> InstallFields,
    string InstallOptionsTitle,
    string ManagerUiTitle,
    IReadOnlyList<string> Capabilities,
    IReadOnlyList<NymphModuleActionInfo> ManagerActions,
    IReadOnlyList<NymphModuleActionGroupInfo> ManagerActionGroups,
    NymphModuleDetailPrimaryActionInfo? DetailPrimaryAction,
    IReadOnlyList<string> DevCapabilities,
    int SortOrder);
