#!/usr/bin/env bash

if [[ -z "${NYMPHS3D_HELPER_ROOT:-}" ]]; then
  if [[ -d /opt/nymphs3d/NymphsCore ]]; then
    NYMPHS3D_HELPER_ROOT=/opt/nymphs3d/NymphsCore
  else
    NYMPHS3D_HELPER_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  fi
fi

if [[ -z "${NYMPHS3D_RUNTIME_ROOT:-}" ]]; then
  NYMPHS3D_RUNTIME_ROOT="${HOME}"
fi

NYMPHS3D_Z_IMAGE_DIR="${NYMPHS3D_Z_IMAGE_DIR:-${NYMPHS3D_N2D2_DIR:-${NYMPHS3D_RUNTIME_ROOT}/Z-Image}}"
NYMPHS3D_N2D2_DIR="${NYMPHS3D_N2D2_DIR:-${NYMPHS3D_Z_IMAGE_DIR}}"
NYMPHS3D_TRELLIS_DIR="${NYMPHS3D_TRELLIS_DIR:-${NYMPHS3D_RUNTIME_ROOT}/TRELLIS.2}"
NYMPHS3D_CUDA_HOME="${NYMPHS3D_CUDA_HOME:-/usr/local/cuda-13.0}"

NYMPHS3D_CACHE_ROOT="${NYMPHS3D_CACHE_ROOT:-${HOME}/.cache}"
NYMPHS3D_HF_HOME="${NYMPHS3D_HF_HOME:-${NYMPHS3D_CACHE_ROOT}/huggingface}"
NYMPHS3D_HF_CACHE_DIR="${NYMPHS3D_HF_CACHE_DIR:-${NYMPHS3D_HF_HOME}/hub}"
NYMPHS3D_HF_DISABLE_XET="${NYMPHS3D_HF_DISABLE_XET:-1}"
NYMPHS3D_N2D2_REPO_URL="${NYMPHS3D_N2D2_REPO_URL:-https://github.com/nymphnerds/Nymphs2D2.git}"
NYMPHS3D_N2D2_REPO_BRANCH="${NYMPHS3D_N2D2_REPO_BRANCH:-main}"
NYMPHS3D_N2D2_REPO_REF="${NYMPHS3D_N2D2_REPO_REF:-655112d1d344914c0b7289fbc97558d123d3ecf5}"
NYMPHS3D_TRELLIS_REPO_URL="${NYMPHS3D_TRELLIS_REPO_URL:-https://github.com/microsoft/TRELLIS.2.git}"
NYMPHS3D_TRELLIS_REPO_BRANCH="${NYMPHS3D_TRELLIS_REPO_BRANCH:-main}"
NYMPHS3D_TRELLIS_REPO_REF="${NYMPHS3D_TRELLIS_REPO_REF:-5565d240c4a494caaf9ece7a554542b76ffa36d3}"
NYMPHS3D_NUNCHAKU_INDEX_URL="${NYMPHS3D_NUNCHAKU_INDEX_URL:-}"
NYMPHS3D_NUNCHAKU_SPEC="${NYMPHS3D_NUNCHAKU_SPEC:-git+https://github.com/nymphnerds/nunchaku.git@78210f92c1f4934a9a81881978f0fa0d9a5cff60}"
NYMPHS3D_U2NET_DIR="${NYMPHS3D_U2NET_DIR:-${HOME}/.u2net}"

configure_nymphs3d_cuda_env() {
  export CUDA_HOME="${NYMPHS3D_CUDA_HOME}"
  export PATH="${CUDA_HOME}/bin:${PATH}"
  export LD_LIBRARY_PATH="${CUDA_HOME}/lib64:${LD_LIBRARY_PATH:-}"
}

configure_nymphs3d_hf_env() {
  export HF_HOME="${NYMPHS3D_HF_HOME}"
  export HF_HUB_CACHE="${NYMPHS3D_HF_CACHE_DIR}"
  export HF_HUB_DISABLE_XET="${NYMPHS3D_HF_DISABLE_XET}"
  if [[ -n "${NYMPHS3D_HF_TOKEN:-}" ]]; then
    export HF_TOKEN="${NYMPHS3D_HF_TOKEN}"
  fi
}
